# Generated by Django 5.2.17 on 2026-09-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_project_fe19a5_idx',
            old_name='tasks_project_status_idx',
        ),
    ]
